### ISSUE TITLE
请问一下怎么添加游戏的CheckSUM存档校验码？

### ISSUE THREAD

**Issue by SvenOu** [OneRice07/GoHAN#1]

**Comment by OneRice07** [comment]
不好意思，工作太忙，回复晚了。
添加游戏checksum需要写代码进源码，然后编译，目前用户无法自定义添加。由于时间关系和程序体积的考虑，当初做GoHAN的时候，并没有将所有的算法集成到GoHAN中，只将目前几个checksum用到的算法加入了，例如CRC16，CRC32等几个常用的。

**Comment by SvenOu** [comment]
哦，谢谢
